# Generated by Django 4.0 on 2021-12-23 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_rename_user_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Enter e-mail address.', max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='MobileNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(help_text='Enter phone number.', max_length=20)),
            ],
        ),
        migrations.RenameField(
            model_name='client',
            old_name='companydesc',
            new_name='company_description',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='fullnameuser',
            new_name='full_name_user',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='namecompany',
            new_name='name_company',
        ),
        migrations.RemoveField(
            model_name='client',
            name='number',
        ),
        migrations.AddField(
            model_name='client',
            name='mobile_number',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='clients.mobilenumber'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.email'),
        ),
    ]
