# Generated by Django 4.0 on 2021-12-23 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_email_mobilenumber_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='email',
        ),
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.ManyToManyField(to='clients.Email'),
        ),
        migrations.RemoveField(
            model_name='client',
            name='mobile_number',
        ),
        migrations.AddField(
            model_name='client',
            name='mobile_number',
            field=models.ManyToManyField(to='clients.MobileNumber'),
        ),
    ]
