# Generated by Django 4.0 on 2021-12-23 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_remove_client_mobile_number_client_mobile_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='mobile_number',
        ),
        migrations.AddField(
            model_name='client',
            name='mobile_number',
            field=models.ManyToManyField(to='clients.MobileNumber'),
        ),
    ]
