# Generated by Django 4.0 on 2021-12-23 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0008_remove_client_mobile_number_client_mobile_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='mobile_number',
        ),
        migrations.DeleteModel(
            name='MobileNumber',
        ),
    ]
