# Generated by Django 4.0 on 2021-12-23 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0011_remove_client_email_client_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='email',
        ),
        migrations.RemoveField(
            model_name='client',
            name='mobile_number',
        ),
        migrations.AddField(
            model_name='email',
            name='client',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='clients.client'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mobilenumber',
            name='client',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='clients.client'),
            preserve_default=False,
        ),
    ]
