# Generated by Django 4.0 on 2021-12-26 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0012_remove_client_email_remove_client_mobile_number_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MobileNumber',
            new_name='Phone',
        ),
    ]
