# Generated by Django 4.0 on 2021-12-26 22:38

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0013_rename_mobilenumber_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='company_description',
            field=tinymce.models.HTMLField(verbose_name='Description'),
        ),
    ]
